let text = [
    "<p>Most of us associate Arabica with high quality deliciousness. In fact, it’s so popular that it makes up around 60 – 70% of the world’s total consumption. Are we correct in placing all our trust in these mysterious beans? Are they the superior bean? Here are the facts…</p><p>Arabica, also known as coffea arabica or Arabian coffee is believed to be the first species of coffee cultivated. This would have been during the 11th century in Ethiopia.</p><p>Today, high quality Arabica is usually grown in South/Central America and Africa.</p><p>It is so popular because of its delicious taste. In the flavour profile you may notice sweetness with hints of caramel, nuts and chocolate. Some blends have a fruitier profile, with flavours of berries. The type of acidity depends on the growing conditions, but many coffee connoisseurs favour Arabica for a pleasant acidity.</p><p>Arabica has the most varietals (at least 40), so I won’t go into detail for every single one. Instead, here are some of the most well-known varietals that you have probably tasted. Browse the shop section to see which products we offer in each varietal. Now you’re familiar with the most popular type of bean, let’s discuss the second most popular…</p><p class='source'>source: <a href='https://www.adamsandrussell.co.uk/types-of-coffee-beans-characteristics/#Arabica' target='_blank'>www.adamsandrussell.co.uk</a></p>",

    "<p>Robusta coffee is characterized by a bitter taste, from neutral to bitter.</p><p>The taste of Robusta is not appreciated by Arabica in terms of purity, natural aroma. Therefore, the price of Robusta is usually much lower than that of Arabica. However, the outstanding feature of this coffee variety is the very high caffeine content, accounting for about 2 – 4% of coffee beans while Arabica has only 1 – 3%.</p><p>However, in fact, when wet-processed Robusta coffee can give higher quality than conventional Arabica varieties (because Arabica has many varieties and not all are good). So the comparison of Arabica and Robusta is sometimes not entirely accurate.</p><p>Robusta Cafe is bitter but has a sweet fragrance, not sour but sweeter than Arabica.</p><p>We can also combine these two flavors together with a neutralizer such as cocoa or chocolate with a certain amount to enjoy the taste better.</p><p>Normally, people often apply the formula: 30% of Arabica coffee, 40% of Robusta and the remaining 30% is a neutral coffee or cocoa. However, if you like to enjoy coffee on your own, you can completely change the recipe above to suit you best.</p><p class='source'>source: <a href='https://asiacom.vn/robusta-coffee-characteristics-flavors-benefits-and-where-to-buy-robusta-coffee/#3_Characteristics_of_the_taste_of_Robusta_coffee' target='_blank'>www.asiacom.vn</a></p>",

    "<p>It's known to have a metallic, woody taste, and is generally a little bitter.</p><p>Recent efforts by groups in Malaysia and Germany have produced crops that are challenging this assumption, leading to promising results. A few crops have been produced that are actually sweeter than a typical Arabica.</p><p>A coffee plant species (Coffea Liberica) that is third in importance among commercially produced coffees behind Arabica (Coffea arabica including Bourbon coffee Heirloom varietal and Typica coffee) and Robusta (Coffea canephora var. robusta), but moreso than Excelsa.</p><p>Liberica coffee trees grow up to 18 meters tall and have large leaves with a leathery surface as well as large seeds (coffee beans).</p><p>The taller trees make harvesting the coffee cherries more difficult, as specialized equipment (machinery) is required, or workers must spend additional time setting up ladders to reach the higher beans.</p><p>The benefit of this, is that Liberica coffee trees have a deeper root system, which means they're more robust and able to access water deeper than other varietals might. They can therefore be grown in harsher climates, and even soils that might not be viable for other trees (clay, peat).</p><p>Worldwide, Liberica makes up only about 1% of total coffee grown. It represents an important source of diversity, especially with concerns about climate change and the looming threat of Arabica's long-term extinction.</p><p class='source'>source: <a href='https://espressocoffeeguide.com/all-about-coffee-2/coffee-plants/liberica-coffee/' target='_blank'>www.espressocoffeeguide.com</a></p>",

    "<p>Despite the issues with its production, when excelsa is farmed and processed with care, it can yield a complex and interesting cup profile.</p><p>Komal says: “In 2020, we processed 200kg of excelsa [coffee] for specialty consumption. We started 2021 with orders that would require us to process at least 5 tonnes of [coffee] to fulfil them.”</p><p>She says that the excelsa bean has a denser mucilage than arabica, and has far fewer soluble solids. This means that existing roast profiles for excelsa shouldn’t be derived from any other bean, and that new curves and best practices must be used.</p><p>In addition, its lower solubility means that excelsa beans may need to be roasted at higher temperatures or for longer periods to reach optimum flavour profiles.</p><p>Roasters who work with excelsa state that medium-light roasts can produce berry-like and fruity notes, as well as woody and popcorn-like flavours. As the roast gets darker, the bean yields a fuller body with notes of chocolate and cream.</p><p>Finally, while natural processing is by far the most common, Komal notes that South India Coffee Co. currently offers double fermented black honey excelsa, with “complex, very berry-like” notes.</p><p class='source'>source: <a href='https://perfectdailygrind.com/2021/05/what-is-excelsa-coffee/' target='_blank'>www.perfectdailygrind.com</a></p>"
]

let buttons = document.getElementsByClassName("btn");
let info = document.getElementsByClassName("info-content")[0];

for(let i = 0; i < buttons.length; i++) {
    buttons[i].addEventListener("click", () => {
        info.innerHTML = text[i];
    })
}